### PR TITLE
user: make voicemailid cascade on delete

### PR DESCRIPTION
**Pull request by pc-m**

### CODE REVIEW

**Review by xxbillouxx — DISMISSED** [review]

**Review by fblackburn1 — CHANGES_REQUESTED** [review]
When deleting voicemail, we should also delete file on filesystem (if we want to do the same thing than API DELETE /voicemails)

**Comment by pc-m** [comment]
> When deleting voicemail, we should also delete file on filesystem (if we want to do the same thing than API DELETE /voicemails) edit: As I don't take this ticket for review, I'll let @pc-m discard this review when it will be fixed

Only the association gets deleted here not the voicemail. The goal is to allow `DELETE /voicemails` to work without having to `DELETE /users/id/voicemails/id` first

**Comment by pc-m** [comment]
> > When deleting voicemail, we should also delete file on filesystem (if we want to do the same thing than API DELETE /voicemails) edit: As I don't take this ticket for review, I'll let @pc-m discard this review when it will be fixed
> 
> Only the association gets deleted here not the voicemail. The goal is to allow `DELETE /voicemails` to work without having to `DELETE /users/id/voicemails/id` first.
> 
> I'm going to recheck the behavior and get back to you @xxbillouxx

I've modified the `CASCADE` to `SET NULL` since it's not a relation table. I do not want to delete users when the voicemail gets deleted.

**Comment by pc-m** [comment]
Out of scope for the creation, I might reopen a similar PR later

**Pull request closed without merging**
