### PR TITLE
Add missing cascade deletion

### PR DESCRIPTION
**Pull request by xxbillouxx**
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/244

### CODE REVIEW

**Comment by xxbillouxx** [comment]
recheck

**Comment by xxbillouxx** [comment]
recheck

**Comment by xxbillouxx** [comment]
recheck

**Review by sduthil — APPROVED** [review]

**Comment by xxbillouxx** [comment]
recheck

**Comment by xxbillouxx** [comment]
recheck

**Comment by xxbillouxx** [comment]
recheck

**Pull request merged**
