### PR TITLE
Wazo 2628 meeting extensions

### PR DESCRIPTION
**Pull request by pc-m**

### CODE REVIEW

**Comment by pc-m** [comment]
recheck

**Comment by bloom1** [comment]
@pc-m is that ready to be reviewed? If so, you forgot to put back the `mergeit` label :grin:

**Comment by pc-m** [comment]
> @pc-m is that ready to be reviewed? If so, you forgot to put back the `mergeit` label grin

Yes it's ready thanks.

**Comment by bloom1** [comment]
Hello @pc-m 

I get the following error when I run the migration script on my stack: 

```
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) column "number" contains null values
```

Does it happen on your stack also?

Thank you!

**Comment by pc-m** [comment]
> Hello @pc-m
> 
> I get the following error when I run the migration script on my stack:
> 
> ```
> sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) column "number" contains null values
> ```
> 
> Does it happen on your stack also?
> 
> Thank you!

You're right, I though that `default` was used as a default for the column creation... I guess not. I'm fixing this

**Review by bloom1 — APPROVED** [review]

**Pull request merged**
