### PR TITLE
WP-595 fix fill_leaveempty_calls

### PR DESCRIPTION
**Pull request by DrPyser**
https://wazo-dev.atlassian.net/browse/WP-595

### CODE REVIEW

**Comment by pc-m** [comment]
The diff is kinda big to know what's happening. Is the only change the `<=` or is something else going on?

**Comment by DrPyser** [comment]
> The diff is kinda big to know what's happening. Is the only change the `<=` or is something else going on?

To summarise the changes, the previous approach is to get all `ENTERQUEUE` events which are in the same call as a `LEAVEEMPTY`, and assumes that the `enterqueue` and `leaveempty` are correlated to the same queue and same subsequence of events. This leads to the bug seen in the ticket.
```
SELECT
        time AS enter_time,
        (select time from queue_log where callid=main.callid AND event='LEAVEEMPTY' LIMIT 1) AS leave_time,
        callid,
        (SELECT id FROM stat_queue WHERE name=queuename) AS stat_queue_id
      FROM queue_log AS main
      WHERE callid IN (SELECT callid FROM queue_log WHERE event = 'LEAVEEMPTY')
            AND event = 'ENTERQUEUE'
            AND time BETWEEN $1 AND $2) AS first;
```

Whereas the new approach first finds `leaveempty` events, and then finds the latest preceding `ENTERQUEUE` event happening on the same queue in the same call. This assumes that any `LEAVEEMPTY` will be preceded by a logically connected `ENTERQUEUE`(one must first enter a queue before leaving). 
```
SELECT main.id, main.callid, main.time AS leave_time, main.queuename, 
        (SELECT time FROM queue_log 
        WHERE callid = main.callid AND queuename = main.queuename 
        AND time <= main.time AND event = 'ENTERQUEUE' 
        ORDER BY time DESC LIMIT 1) AS enter_time, 
        stat_queue.id as stat_queue_id 
    FROM queue_log AS main 
    LEFT JOIN stat_queue ON stat_queue.name = main.queuename
    WHERE event='LEAVEEMPTY'
```
I changed the structure to use CTE in order to separate the crux of the logic from other details.

**Comment by pc-m** [comment]
> > The diff is kinda big to know what's happening. Is the only change the `<=` or is something else going on?
> 
> To summarise the changes, the previous approach is to get all `ENTERQUEUE` events which are in the same call as a `LEAVEEMPTY`, and assumes that the `enterqueue` and `leaveempty` are correlated to the same queue and same subsequence of events. This leads to the bug seen in the ticket.
> 
> ```
> SELECT
>         time AS enter_time,
>         (select time from queue_log where callid=main.callid AND event='LEAVEEMPTY' LIMIT 1) AS leave_time,
>         callid,
>         (SELECT id FROM stat_queue WHERE name=queuename) AS stat_queue_id
>       FROM queue_log AS main
>       WHERE callid IN (SELECT callid FROM queue_log WHERE event = 'LEAVEEMPTY')
>             AND event = 'ENTERQUEUE'
>             AND time BETWEEN $1 AND $2) AS first;
> ```
> 
> Whereas the new approach first finds `leaveempty` events, and then finds the latest preceding `ENTERQUEUE` event happening on the same queue in the same call. This assumes that any `LEAVEEMPTY` will be preceded by a logically connected `ENTERQUEUE`(one must first enter a queue before leaving).
> 
> ```
> SELECT main.id, main.callid, main.time AS leave_time, main.queuename, 
>         (SELECT time FROM queue_log 
>         WHERE callid = main.callid AND queuename = main.queuename 
>         AND time <= main.time AND event = 'ENTERQUEUE' 
>         ORDER BY time DESC LIMIT 1) AS enter_time, 
>         stat_queue.id as stat_queue_id 
>     FROM queue_log AS main 
>     LEFT JOIN stat_queue ON stat_queue.name = main.queuename
>     WHERE event='LEAVEEMPTY'
> ```
> 
> I changed the structure to use CTE in order to separate the crux of the logic from other details.

Makes perfect sense, thanks for the explanation :)

**Review by pc-m — DISMISSED** [review]

**Comment by DrPyser** [comment]
> Please rebase your migration script Then add mergeit tag when ready Then you can discard my approval

Done, thanks!

**Pull request merged**
